name: g-track-frontend deployment

on:
  push:
    branches: [ main ]
  release:
    types: [ published ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'

      - uses: actions/cache@v3
        with:
          path: |
            .angular/cache
          key: angular-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            angular-cache-

      - name: Install dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/

      - name: Preparing SSH Key
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.ID_RSA }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan g-track.eu > ~/.ssh/known_hosts

      - name: Deploy Stage
        if: ${{ github.event_name == 'push' }}
        run: |
          rsync -avzuh -e 'ssh' ./dist/g-track-frontend/ gtrack@g-track.eu:/opt/gtrack/stage/frontend/ --progress --delete

      - name: Deploy Production
        if: ${{ github.event_name == 'release' }}
        run: |
          rsync -avzuh -e 'ssh' ./dist/g-track-frontend/ gtrack@g-track.eu:/opt/gtrack/prod/frontend/ --progress --delete
