name: Lint
on:
  pull_request:
  push:
    branches: [ "main" ]
permissions: { contents: read }
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: actions/setup-node@v4
        with: { node-version: "20" }
      - run: npm ci --loglevel=error
      - run: npm run lint:ci
